# Generated by Django 2.1.2 on 2019-02-20 11:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTableType1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('entryTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='BuyTableType2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('entryTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='BuyTableType3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('entryTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='BuyTableType4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('entryTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='BuyTableType5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('entryTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sharePrice', models.IntegerField(default=0)),
                ('totalNoOfShares', models.IntegerField(default=0)),
                ('sharesLeft', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensex', models.FloatField(default=0)),
                ('spread', models.IntegerField(default=0)),
                ('LiveText', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=-1)),
                ('numberOfShares', models.IntegerField(default=0)),
                ('cash', models.IntegerField(default=380000)),
                ('netWorth', models.IntegerField(default=0)),
                ('numberOfCompanies', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellTableType1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellPrice', models.IntegerField(default=0)),
                ('sellShares', models.IntegerField(default=0)),
                ('entryTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTableType2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellPrice', models.IntegerField(default=0)),
                ('sellShares', models.IntegerField(default=0)),
                ('entryTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTableType3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellPrice', models.IntegerField(default=0)),
                ('sellShares', models.IntegerField(default=0)),
                ('entryTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTableType4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellPrice', models.IntegerField(default=0)),
                ('sellShares', models.IntegerField(default=0)),
                ('entryTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTableType5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellPrice', models.IntegerField(default=0)),
                ('sellShares', models.IntegerField(default=0)),
                ('entryTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=0)),
                ('noShares', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
                ('buysell', models.BooleanField(default=0)),
                ('transacTime', models.DateTimeField(default=datetime.datetime.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyOwned', models.IntegerField(default=0)),
                ('noOfCompanyShares', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile'),
        ),
        migrations.AddField(
            model_name='buytabletype5',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company'),
        ),
        migrations.AddField(
            model_name='buytabletype5',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile'),
        ),
        migrations.AddField(
            model_name='buytabletype4',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company'),
        ),
        migrations.AddField(
            model_name='buytabletype4',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile'),
        ),
        migrations.AddField(
            model_name='buytabletype3',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company'),
        ),
        migrations.AddField(
            model_name='buytabletype3',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile'),
        ),
        migrations.AddField(
            model_name='buytabletype2',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company'),
        ),
        migrations.AddField(
            model_name='buytabletype2',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile'),
        ),
        migrations.AddField(
            model_name='buytabletype1',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company'),
        ),
        migrations.AddField(
            model_name='buytabletype1',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile'),
        ),
    ]
