# Generated by Django 2.2.1 on 2019-08-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='startNews',
            field=models.BooleanField(default=False),
        ),
    ]
