# Generated by Django 2.1.2 on 2019-06-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0004_auto_20190224_0618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyTableType5',
            new_name='BuyTable',
        ),
        migrations.RenameModel(
            old_name='SellTableType1',
            new_name='SellTable',
        ),
        migrations.RenameModel(
            old_name='UserTable',
            new_name='UserShareTable',
        ),
        migrations.RemoveField(
            model_name='buytabletype1',
            name='company',
        ),
        migrations.RemoveField(
            model_name='buytabletype1',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='buytabletype2',
            name='company',
        ),
        migrations.RemoveField(
            model_name='buytabletype2',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='buytabletype3',
            name='company',
        ),
        migrations.RemoveField(
            model_name='buytabletype3',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='buytabletype4',
            name='company',
        ),
        migrations.RemoveField(
            model_name='buytabletype4',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='selltabletype2',
            name='company',
        ),
        migrations.RemoveField(
            model_name='selltabletype2',
            name='proile',
        ),
        migrations.RemoveField(
            model_name='selltabletype3',
            name='company',
        ),
        migrations.RemoveField(
            model_name='selltabletype3',
            name='proile',
        ),
        migrations.RemoveField(
            model_name='selltabletype4',
            name='company',
        ),
        migrations.RemoveField(
            model_name='selltabletype4',
            name='proile',
        ),
        migrations.RemoveField(
            model_name='selltabletype5',
            name='company',
        ),
        migrations.RemoveField(
            model_name='selltabletype5',
            name='proile',
        ),
        migrations.DeleteModel(
            name='BuyTableType1',
        ),
        migrations.DeleteModel(
            name='BuyTableType2',
        ),
        migrations.DeleteModel(
            name='BuyTableType3',
        ),
        migrations.DeleteModel(
            name='BuyTableType4',
        ),
        migrations.DeleteModel(
            name='SellTableType2',
        ),
        migrations.DeleteModel(
            name='SellTableType3',
        ),
        migrations.DeleteModel(
            name='SellTableType4',
        ),
        migrations.DeleteModel(
            name='SellTableType5',
        ),
    ]
