# Generated by Django 2.1.2 on 2019-06-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0005_auto_20190610_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tableType',
        ),
    ]
