# Generated by Django 2.1.2 on 2019-06-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0007_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTable0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
    ]
