# Generated by Django 2.1.2 on 2019-06-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0009_auto_20190611_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tempName',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
