# Generated by Django 2.1.2 on 2019-06-11 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0010_company_tempname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTable_ACC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Ambuja_Cement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Apollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Avenue_Supermarkets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Axis_Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Bajaj_Electrical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Bharti_Airtel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Bombay_Dyeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_CEAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Cipla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Crompton_Greaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Dena_Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Dr_Reddys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Eicher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Eros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Future_Retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_HDFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_HPCL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_HUL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Infosys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_ITC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Jindal_Steel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Jio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_JK_Lakshmi_Cement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_LandT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Maruti_Suzuki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Mindtree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_MRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Nestle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_ONGC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Patanjali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_PVR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Raymonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_RCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_RIL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Sharp_India',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Sun_Pharma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Tata_Motors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Tata_Steel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_TCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Vedanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_ACC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Ambuja_Cement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Apollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Avenue_Supermarkets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Axis_Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Bajaj_Electrical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Bharti_Airtel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Bombay_Dyeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_CEAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Cipla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Crompton_Greaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Dena_Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Dr_Reddys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Eicher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Eros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Future_Retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_HDFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_HPCL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_HUL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Infosys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_ITC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Jindal_Steel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Jio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_JK_Lakshmi_Cement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_LandT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Maruti_Suzuki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Mindtree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_MRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Nestle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_ONGC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Patanjali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_PVR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Raymonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_RCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_RIL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Sharp_India',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Sun_Pharma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Tata_Motors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Tata_Steel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_TCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Vedanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
    ]
