# Generated by Django 2.1.2 on 2019-06-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0011_buytable_acc_buytable_ambuja_cement_buytable_apollo_buytable_avenue_supermarkets_buytable_axis_bank_'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTable_CompanyTemp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_CompanyTemp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Company')),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
    ]
