# Generated by Django 2.1.2 on 2019-06-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0017_auto_20190613_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTable_ACC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=191)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_AmbujaCement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=187)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Apollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=197)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_AvenueSupermarkets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=181)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_AxisBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=178)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_BajajElectrical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=198)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_BhartiAirtel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=177)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_BombayDyeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=201)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_CEAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=199)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Cipla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=186)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_CromptonGreaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=195)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_DenaBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=205)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_DrReddys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=189)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Eicher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=184)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Eros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=206)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_FutureRetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=192)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_HDFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=170)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_HPCL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=188)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_HUL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=171)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=193)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Infosys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=173)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_ITC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=172)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_JindalSteel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=194)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Jio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=208)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_JKLakshmiCement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=204)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_LT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=176)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_MarutiSuzuki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=174)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Mindtree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=196)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_MRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=190)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Nestle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=180)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_ONGC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=175)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Patanjali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=209)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_PVR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=200)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Raymonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=203)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_RCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=202)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_RIL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=168)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_SharpIndia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=207)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_SunPharma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=179)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_TataMotors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=183)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_TataSteel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=185)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_TCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=169)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable_Vedanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=182)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_ACC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=191)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_AmbujaCement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=187)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Apollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=197)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_AvenueSupermarkets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=181)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_AxisBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=178)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_BajajElectrical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=198)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_BhartiAirtel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=177)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_BombayDyeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=201)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_CEAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=199)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Cipla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=186)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_CromptonGreaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=195)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_DenaBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=205)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_DrReddys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=189)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Eicher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=184)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Eros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=206)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_FutureRetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=192)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_HDFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=170)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_HPCL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=188)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_HUL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=171)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=193)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Infosys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=173)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_ITC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=172)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_JindalSteel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=194)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Jio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=208)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_JKLakshmiCement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=204)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_LT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=176)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_MarutiSuzuki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=174)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Mindtree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=196)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_MRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=190)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Nestle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=180)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_ONGC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=175)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Patanjali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=209)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_PVR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=200)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Raymonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=203)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_RCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=202)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_RIL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=168)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_SharpIndia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=207)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_SunPharma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=179)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_TataMotors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=183)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_TataSteel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=185)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_TCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=169)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellTable_Vedanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(default=182)),
                ('bidPrice', models.IntegerField(default=0)),
                ('bidShares', models.IntegerField(default=0)),
                ('proile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Profile')),
            ],
        ),
    ]
