# Generated by Django 2.1.2 on 2019-06-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0018_buytable_acc_buytable_ambujacement_buytable_apollo_buytable_avenuesupermarkets_buytable_axisbank_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='Price',
            new_name='bidPrice',
        ),
        migrations.RenameField(
            model_name='userhistory',
            old_name='buysell',
            new_name='buySell',
        ),
        migrations.RenameField(
            model_name='usersharetable',
            old_name='Price',
            new_name='bidPrice',
        ),
    ]
