# Generated by Django 2.1.2 on 2019-06-13 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0023_auto_20190613_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytable',
            name='transactionTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='selltable',
            name='transactionTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='buySell',
            field=models.BooleanField(default=1),
        ),
    ]
