# Generated by Django 2.2.2 on 2019-06-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0024_auto_20190613_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='numberOfCompanies',
        ),
    ]
