# Generated by Django 2.1.2 on 2019-06-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0025_remove_profile_numberofcompanies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersharetable',
            name='bidPrice',
        ),
    ]
