# Generated by Django 2.1.2 on 2019-06-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0026_remove_usersharetable_bidprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='company',
        ),
    ]
