# Generated by Django 2.1.2 on 2019-06-14 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0028_global_leaderboardsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='LeaderBoardUpdateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
