# Generated by Django 2.1.2 on 2019-06-14 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0029_global_leaderboardupdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='bidRangePercent',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
