# Generated by Django 2.1.2 on 2019-06-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0031_auto_20190614_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='registrationKey',
            field=models.CharField(default='abcde', max_length=20),
        ),
    ]
