# Generated by Django 2.2.2 on 2019-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0032_global_registrationkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='startStopMarket',
            field=models.BooleanField(default=True),
        ),
    ]
