# Generated by Django 2.1.2 on 2019-06-16 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0033_global_startstopmarket'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
