# Generated by Django 2.1.2 on 2019-06-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0034_news_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='NewsCounter',
            field=models.IntegerField(default=0),
        ),
    ]
