# Generated by Django 2.1.2 on 2019-02-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0002_auto_20190220_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='type',
            new_name='tableType',
        ),
    ]
