# Generated by Django 2.1.5 on 2019-02-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0003_auto_20190220_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='endPointer',
            new_name='basePointer',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='startPointer',
            new_name='buyEndPointer',
        ),
        migrations.RenameField(
            model_name='selltabletype1',
            old_name='sellPrice',
            new_name='bidPrice',
        ),
        migrations.RenameField(
            model_name='selltabletype1',
            old_name='sellShares',
            new_name='bidShares',
        ),
        migrations.RenameField(
            model_name='selltabletype2',
            old_name='sellPrice',
            new_name='bidPrice',
        ),
        migrations.RenameField(
            model_name='selltabletype2',
            old_name='sellShares',
            new_name='bidShares',
        ),
        migrations.RenameField(
            model_name='selltabletype3',
            old_name='sellPrice',
            new_name='bidPrice',
        ),
        migrations.RenameField(
            model_name='selltabletype3',
            old_name='sellShares',
            new_name='bidShares',
        ),
        migrations.RenameField(
            model_name='selltabletype4',
            old_name='sellPrice',
            new_name='bidPrice',
        ),
        migrations.RenameField(
            model_name='selltabletype4',
            old_name='sellShares',
            new_name='bidShares',
        ),
        migrations.RenameField(
            model_name='selltabletype5',
            old_name='sellPrice',
            new_name='bidPrice',
        ),
        migrations.RenameField(
            model_name='selltabletype5',
            old_name='sellShares',
            new_name='bidShares',
        ),
        migrations.AddField(
            model_name='company',
            name='buyStartPointer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='sellEndPointer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='sellStartPointer',
            field=models.IntegerField(default=0),
        ),
    ]
