# Generated by Django 2.1.2 on 2019-06-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0022_auto_20190613_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buytable',
            name='transactionTime',
        ),
        migrations.RemoveField(
            model_name='selltable',
            name='transactionTime',
        ),
    ]
